### ISSUE TITLE
Estética

### ISSUE THREAD

**Issue by DanBaDo** [Brox13/Traffic-Light-React#1]
No podemos olvidar que en el frontend estamos creando la parte de la aplicación que el usuario ve. No podemos dejar pasar defectos  visuales importantes. Tenemos que centrar ese semáforo con su poste.
![image](https://user-images.githubusercontent.com/85959254/181808863-38bc2e40-d6a0-4118-a446-ad7b1b69f2ed.png)

**Comment by Brox13** [comment]
Lo hice con el inspeccionar pantalla y lo deje mal colocado. Solucionado!!
